### ISSUE TITLE
Jid resource part fails on @ and / chars

### ISSUE THREAD

**Issue by haskellGardener** [pontarius/pontarius-xmpp#98]
Sadly, the XML pickler chokes with 'xmppBind: JID could not be unpickled' if the resource part contains @ or / chars.

RFC: 6122
  Section  2.4.  Resourcepart

  XMPP entities SHOULD consider resourceparts to be opaque strings
  and SHOULD NOT impute meaning to any given resourcepart. In particular:

    Use of the '/' character as a separator between the domainpart and
    the resourcepart does not imply that XMPP addresses are
    hierarchical in the way that, say, HTTP addresses are
    hierarchical; thus for example an XMPP address of the form
    <localpart@domainpart/foo/bar> does not identify a resource "bar"
    that exists below a resource "foo" in a hierarchy of resources
    associated with the entity "localpart@domain".

    The '@' character is allowed in the resourcepart and is often used
    in the "nick" shown in XMPP chatrooms. For example, the JID
    <room@chat.example.com/user@host> describes an entity who is an
    occupant of the room <room@chat.example.com> with an (asserted)
    nick of <user@host>. However, chatroom services do not necessarily
    check such an asserted nick against the occupant's real JID.

**Comment by jonkri** [comment]
Hi!

Thanks for reporting this!

I guess the problem is on this line:

https://github.com/pontarius/pontarius-xmpp/blob/eeef91e8827bebd0637748898c79e2ea26ccc1fc/source/Network/Xmpp/Types.hs#L1176

I interpret http://xmpp.org/rfcs/rfc6122.html#addressing-resource as that it's acceptable for the resourcepart to contain '/' as well. So perhaps we should simply switch to using <code>takeByteString</code> there instead.

@Philonous: Do you perhaps have any thoughts on this?

Cheers!

**Comment by Philonous** [comment]
Seems right to me, except of course we want takeText ;)

**Comment by Philonous** [comment]
> [jid|foo/bar/quux@bla/|]
parseJid "foo/bar/quux@bla/"

**Comment by haskellGardener** [comment]
Cool!
